server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/FpyrypT/config
          username: myusername!
          password: mypassword!
          clone-on-start: true
